version: '3.8'

services:
  app:
    image: openjdk:17-alpine
    build:
      context: .
      dockerfile: Dockerfile
      args:
        JAR_FILE: target/vivefacilv1-0.0.1-SNAPSHOT.jar
    ports:
      - "8080:8080"
    entrypoint: ["java", "-jar", "/app.jar"]
    volumes:
      - ./target/vivefacilv1-0.0.1-SNAPSHOT.jar:/app.jar
    environment:
      - SPRING_PROFILES_ACTIVE=cloud